# Generated by Django 5.1.4 on 2024-12-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=100)),
                ('Department_Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
