# Generated by Django 5.1.5 on 2025-01-23 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Department_Description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Department_Name',
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='department_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
